javascripts:
  interfaith:
    - public/javascripts/json2.js
    - public/javascripts/underscore-min.js
    - public/javascripts/backbone-min.js
    - public/javascripts/backbone.js
    - app/views/pos/*.jst